[package]
name = "ssb-sql-napi"
version = "1.0.0"
authors = ["Piet Geursen <pietgeursen@gmail.com>"]
license = "AGPL3"

[lib]
name = "ssb_sql_napi"
crate-type = ["staticlib"]

[dependencies]
serde = "1.0.80"
serde_cbor = "0.9.0"
serde_derive = "1.0.80"

[dependencies.serde_json] 
version = "1.0.32"
